### PR TITLE
genie-chrome: files/testem.js is not ignored anymore

### LINKED ISSUE #2: files in blueprints/genie-chrome not in npm packages
Hi,

For an unknown reason, it seems that files directory in `blueprints/genie-chrome`  is not present in npm packages. I do not understand why.

You can see that downloading packages manually : [0.0.6](https://registry.npmjs.org/ember-addon-genie/-/ember-addon-genie-0.0.6.tgz) or [0.0.5](https://registry.npmjs.org/ember-addon-genie/-/ember-addon-genie-0.0.5.tgz)

In addition, I have a side suggestion: could the `genie-chrome` blueprint be changed to update `temtem.js` instead of replacing it (as it it done for `genie-coverage` [here](https://github.com/bmeurant/ember-addon-genie/blob/master/blueprints/genie-coverage/index.js#L20)) ?  I can open a PR if you agree.

### PR DESCRIPTION
**Pull request by bmeurant**
See #2 for bug description.

.npmignore was ignoring all testem.js files in any subdirectory. This fix ignore only file in the root directory, allowing to provide testem.js file in blueprints. closes #2

Maybe be it is worth to consider adding `/` behind other root files to allow future usages ?

### CODE REVIEW

**Comment by offirgolan** [comment]
> Maybe be it is worth to consider adding / behind other root files to allow future usages ?

I think that would be a good idea. Can you add that in this PR?

**Comment by bmeurant** [comment]
Done. :smirk:

**Comment by offirgolan** [comment]
Oh man I totally thought I merged this PR... really sorry for the delay here!

**Comment by offirgolan** [comment]
@bmeurant Thank you! 😺

**Comment by bmeurant** [comment]
np :smile: you're welcome

**Pull request merged**
